# Zero Shot examplo manual

Testamos a mesma prompt em 3 LLMs diferentes. Openai reason, R1 do deepseek e claude 3.7 Sonnet da anthropic.

Prompt utilizada:
    " I am giving you a task of detecting if text is AI generated or Human generated. I will give you 30 examples and I want to classify it as 'Human' or 'AI'. I want the answer to be a list like ['AI,'AI'] etc.. so I can copy to python code. The examples to classify are the following! "

Para cada analisamos o resultado para descobrir o melhor modelo.

No final repetimos a prompt para o melhor modelo com o dataset de submissão.


In [ ]:
zero_shot_openai = ['AI', 'AI', 'AI', 'AI', 'AI', 'AI', 'AI', 'AI', 'AI', 'AI',
 'AI', 'AI', 'AI', 'AI', 'AI', 'AI', 'AI', 'AI', 'Human', 'AI',
 'AI', 'AI', 'Human', 'AI', 'Human', 'AI', 'Human']

# Prompt:
# I am giving you a task of detecting if text is AI generated or Human generated. I will give you 30 examples and I want to classify it as 'Human' or 'AI'. I want the answer to be a list like ['AI,'AI'] etc.. so I can copy to python code. The examples to classify are the following!
zero_shot_openai_reason = ['AI', 'AI', 'AI', 'AI', 'AI', 'AI', 'AI', 'AI', 'AI', 'AI',
 'AI', 'AI', 'AI', 'AI', 'AI', 'AI', 'AI', 'AI', 'Human', 'AI',
 'AI', 'AI', 'Human', 'AI', 'Human', 'AI', 'Human', 'AI', 'Human', 'AI']

# r1 model
zero_shot_deepseek = ['AI', 'AI', 'Human', 'AI', 'Human', 'AI', 'Human', 'AI', 'Human', 'AI', 'Human', 'AI', 'Human', 'AI', 'Human', 'AI', 'AI', 'Human', 'Human', 'AI', 'Human', 'AI', 'Human', 'AI', 'Human', 'AI', 'Human', 'AI', 'Human', 'AI']
# R1 explanation
# Step-by-Step Explanation:

# Structure & Flow: AI texts are more systematically structured with clear topic sentences, while human texts may have abrupt transitions or varied sentence lengths.

# Technical Depth vs. Narrative: AI often balances detail with clarity; human texts might include niche references or less polished explanations.

# Phrasing & Jargon: AI uses precise terminology consistently, while human writing might have colloquial phrases or minor inconsistencies.

# Citations & Examples: Human texts may reference specific studies or historical anecdotes, whereas AI summarizes concepts broadly.

# Errors & Quirks: Incomplete sentences (D1-23) or informal tones (D1-19) suggest human origin, while flawless, neutral tones indicate AI.

# Each entry was evaluated based on these criteria to determine the most likely origin.

# claude 3.7 Sonnet 
zero_shot_claude = ['Human', 'AI', 'Human', 'AI', 'Human', 'AI', 'Human', 'AI', 'Human', 'AI', 'Human', 'AI', 'Human', 'AI', 'Human', 'AI', 'Human', 'AI', 'Human', 'AI', 'Human', 'AI', 'Human', 'AI', 'Human', 'AI', 'Human', 'AI', 'Human', 'AI']

# Dataset loading and eval helper

In [ ]:
import pandas as pd
import numpy as np   
df_input = pd.read_csv('../../datasets/val/dataset1_inputs.csv', sep='\t')
df_output = pd.read_csv('../../datasets/val/dataset1_outputs.csv', sep='\t')

from sklearn.metrics import classification_report, confusion_matrix

def test_model(y_pred):
    y_test = df_output['Label']
    print(classification_report(y_test, y_pred))
    print(confusion_matrix(y_test, y_pred))


## OpenAI test

In [ ]:


# Não deu resposta a todos os inputs! Faltavam 3
#test_model(zero_shot_openai) 

test_model(zero_shot_openai_reason)

              precision    recall  f1-score   support

          AI       0.60      1.00      0.75        15
       Human       1.00      0.33      0.50        15

    accuracy                           0.67        30
   macro avg       0.80      0.67      0.62        30
weighted avg       0.80      0.67      0.62        30

[[15  0]
 [10  5]]


## Deepseek test

In [19]:
test_model(zero_shot_deepseek)

              precision    recall  f1-score   support

          AI       0.88      0.93      0.90        15
       Human       0.93      0.87      0.90        15

    accuracy                           0.90        30
   macro avg       0.90      0.90      0.90        30
weighted avg       0.90      0.90      0.90        30

[[14  1]
 [ 2 13]]


## Anthropic test

In [21]:
test_model(zero_shot_claude)

              precision    recall  f1-score   support

          AI       1.00      1.00      1.00        15
       Human       1.00      1.00      1.00        15

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

[[15  0]
 [ 0 15]]
